# Generated by Django 5.1.6 on 2026-03-10 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_id'),
        ('accounts', '0003_alter_user_email'),
    ]

    operations = [
    ]
