# Generated by Django 5.1.6 on 2026-03-09 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectteam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectTeam',
        ),
    ]
