# Generated by Django 5.1.6 on 2026-03-09 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_project'),
        ('tasks', '0005_alter_task_project_nullable'),
    ]

    operations = [
    ]
