# Generated by Django 5.1.6 on 2026-03-10 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_id'),
        ('tasks', '0006_merge_20260310_0033'),
    ]

    operations = [
    ]
