# Generated by Django 5.1.6 on 2026-02-28 11:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('size', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('last_user_number', models.IntegerField(default=0)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True)),
                ('can_manage_company', models.BooleanField(default=False)),
                ('can_manage_roles', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_create_project', models.BooleanField(default=False)),
                ('can_assign_task', models.BooleanField(default=False)),
                ('can_view_all_tasks', models.BooleanField(default=False)),
                ('can_view_team_tasks', models.BooleanField(default=False)),
                ('can_view_assigned_tasks', models.BooleanField(default=False)),
                ('can_update_task_status', models.BooleanField(default=False)),
                ('can_view_project_progress', models.BooleanField(default=False)),
                ('can_manage_hr', models.BooleanField(default=False)),
                ('can_approve_leave', models.BooleanField(default=False)),
                ('can_view_attendance', models.BooleanField(default=False)),
                ('can_manage_payroll', models.BooleanField(default=False)),
                ('level', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='INVITED', max_length=20)),
                ('invite_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('account_no', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.role')),
            ],
        ),
    ]
